### ISSUE TITLE
Add full filtering and ordering to full text search

### ISSUE THREAD

**Issue by bedeho** [Joystream/hydra#127]
Currently its not possible to filter and order on full text search results, this is important, for example in atlas you want to not listed curated content in full text search results.

**Comment by bedeho** [comment]
It was pointed out by @dzhelezov that automatically deriving this for some full text search is unlikely to be possible, because the return type `Foo` in  `my_search(): Foo` does not need to be an entity type, e.g. it may be a union type, hence it is not possible to generally derive.

A second best alternative here would be to allow the input schema developer to manually define (non-entity) input types `T_1,..., T_N`, and then when defining the search query you can reference these types by doing something like

```graphql
search {
 params : {
}
}
```

**Comment by bedeho** [comment]
I was asked to give an example to show what this would look like.

# Single Entity

Assume I had the following input schema

```graphql

type Foo @entity {
  age: Int!
  name: String @fulltext(query: "my_query")
}

```

Then I would expect something like the following API

```graphql

type FooWhereInput {
  /* auto-generated as before */
}

type Query {
  my_query(
    query_string: String
    where: FooWhereInput

    /* pagination stuff, not sure if it looks like this anymore, this is old-style*/
    skip: Int
    after: String
    before: String
    first: Int
    last: Int
  ) : [Foo]
}

```

# Multiple Entity

Assume I had the following input schema

```graphql

type Foo @entity {
  age: Int!
  name: String @fulltext(query: "my_query")
}

type Bar @entity {
  isMale: Boolean
  bio: String @fulltext(query: "my_query")
}

```

Then I would expect something like the following API

```graphql

type FooWhereInput {
  /* auto-generated as before */
}

type BarWhereInput {
  /* auto-generated as before */
}

union my_query_result = Foo | Bar

type Query {
  my_query(
    query_string: String
    where_foo: FooWhereInput
    where_bar: BarWhereInput

    /* pagination stuff, not sure if it looks like this anymore, this is old-style*/
    skip: Int
    after: String
    before: String
    first: Int
    last: Int

  ) : [my_query_result]
}

```

**Comment by dzhelezov** [comment]
This makes sense, the filtering then should translate into SQL of the sorts

```
SELECT * from foo_bar_doc_view where (<text query here>) AND ((type = 'Foo' and (whereinputs for Foo)) OR (type = 'Bar' and (where inputs for Bar))) AND (pagination clauses) order by rank
```

Here `foo_bar_doc_view` is a flattenned view containing both Foo and Bar fields together with a text index on the text fields of interest. 

The only remaining question here: do we always order by rank calculated as the search similarity score?

**Comment by bedeho** [comment]
I think, unless until we see a direct need for something else.

**Comment by ondratra** [comment]
This PR has been solved in https://github.com/Joystream/hydra/pull/179.
