### ISSUE TITLE
Empty variants

### ISSUE THREAD

**Issue by bedeho** [Joystream/hydra#186]
It is frequently required to have empty variant cases, but apparently this is currently not possible. Could it be fixed so that there is no need for dummy fields in the input schema, database or API?

**Comment by dzhelezov** [comment]
GraphQL does not seem to allow empty types: https://github.com/graphql/graphql-spec/issues/568

**Comment by bedeho** [comment]
Too bad, that's a bit of a blunder on their end, to quote

> It seems like a big oversight that graphql supports tagged union types but doesn’t seem to understand not all members of the union need to have additional associated data to be meaningful.
