### ISSUE TITLE
Separate and includable input schema files

### ISSUE THREAD

**Issue by bedeho** [Joystream/hydra#188]
Its getting exceedingly hard to manage everything in one file, its quite clearly not going to scale, so being able to have separate files where one can include one into another as a dependency, similar to C/C++ header files in a preprocessing stage.

**Comment by dzhelezov** [comment]
That's doable and shouldn't be hard to implement

**Comment by bedeho** [comment]
That would be great, would we be able to preserve line numbers in parsing errors that match the original files?

**Comment by dzhelezov** [comment]
We don’t track line numbers when an error is thrown, just report the name of the entity

**Comment by bedeho** [comment]
Ok, guess its a moot point then, looking forward to trying when available.

**Comment by bedeho** [comment]
I think the simplest way to do this, without having to deal with dependencies problems, is perhaps to just allow the manifest to take multiple input file entries, and not introduce some complex directive or other means of including schema files into each other. That buys us the basic ability to break things up we need.
