### ISSUE TITLE
Succinct interface implementation

### ISSUE THREAD

**Issue by bedeho** [Joystream/hydra#192]
It gets extremly verbose to have to reiterate the exact same fields in any entity implementor of an interface. We for example have an `Event` interface like this

```graphql
interface Event @entity {

  "Event identifier"
  id: ID!

  "Possible extrinsic in which"
  inExtrinsic: Extrinsic

  "Block in which event was emitted."
  inBlock: Block!
}
```
  
and currently we have to repeat all these fields across many dusins of specific events implementing this interface.

Can we drop this requirement?

**Comment by metmirr** [comment]
It comes from graphql spec https://spec.graphql.org/June2018/#sec-Interfaces so I am not sure if it is a good idea to drop that.

**Comment by bedeho** [comment]
Ok thanks!
