### ISSUE TITLE
Hydra indexer API

### ISSUE THREAD

**Issue by dzhelezov** [Joystream/hydra#24]
Basic indexer state queries:
--------
This issue outlines the REST API methods to be exposed by the Hydra Indexer API. 

`GET /api/indexer`: Returns the current state of the indexer:
- current indexer head
- current substrate chain head

`GET /api/processor/:id`: Returns info about the mappings processor with given id:
- Processor name
- Processor DB schema
- Last processed event id
- Total number of processed events so far
- Last scanned block
- List of events the processor handles 

Nice to have:
---------
`POST /api/subsrcribe` with body: `{ events: [events_to_subscribe], from_event: <event_id>, chunk_size: <num> }` 
Returns `{ cursor: <cursor_id>, total: <total number of events>}`
Creates a subscription to given events, retrievable by cursor_id.

`POST /api/events/:cursor_id`: Retrieve next <chunk_size> events with a given filter. 
Returns:
`{
  events: [],
  ...
}`

`GET /api/event/:event_name`: Retrieve documentation for the given event
`GET /api/extrinsic/:exrtrinsic_name`: Retrieve documentation for the given extrinsic, for each runtime upgrade
`GET /api/module/:module`: Get all versions of the runtime, and for each runtime version list all events and extrinsics 

Even nicer to have:
--------
Deploy a new mapping processor by uploading a tgz archive

**Comment by bedeho** [comment]
1. Wouldnt it be nice to use GraphQL for these APIs also, as they treat subscriptions, queries and mutations in one uniform way.
2. This appears to have the indexer node serve up an API that contains information about what is being processed, this conflicts with my understanding of what we are trying to achieve, but also aligns with prior confusion in our discussions about write conflicts. My understanding is that we were trying to have an architecture like this.

![hydra_architecture](https://user-images.githubusercontent.com/437292/92991292-445e3680-f4e3-11ea-9949-339e79af6521.png)

**Comment by dzhelezov** [comment]
Summing up the Hydra call on  14.09: we'll go with a single processor set-up sourcing from the Indexer API, which we make GraphQL based as suggested. Reference: https://github.com/Joystream/hydra/issues/10#issuecomment-692010282
