### ISSUE TITLE
Multiple order by fields

### ISSUE THREAD

**Issue by dzhelezov** [Joystream/hydra#282]
Currently orderBy accepts only a single field, but it would be nice to be able to order by mulple, providing an array of order by expressions (e.g. `orderBy: [ filed1_DESC, field2_ASC ]`)

**Comment by bedeho** [comment]
As part of this
- move Warthog fork into Joystream org.
- publish as separate package on NPM, and use this dependency in hydra.
- merge in some branch `<fill in name>` of upstream Warthog which has multiple fields in ordering support.

**Comment by dzhelezov** [comment]
Introduced in v3: https://github.com/Joystream/hydra/pull/378
