### ISSUE TITLE
Missing BN import in the variants template

### ISSUE THREAD

**Issue by dzhelezov** [Joystream/hydra#284]
I found a bug in Hydra (still present in the newest 2.1.0-beta.2) 
`yarn build` with input schema using BigInt fails -> src/modules/variants/variants.model.ts(44,11): error TS2304: Cannot find name 'BN'. The file is missing import of BN.js. Error can be replicated by downloading https://github.com/ondratra/joystream/tree/query_node_mappings , then 
`cd query-node; yarn; yarn build`

**Comment by ondratra** [comment]
Also, after this error is overcome, there will be the next one that we already encountered in the earlier hydra version, but it's probably still not fixed. In variants files, multiple `import` for the same resource is generated when used multiple times in schema's single entity.

`src/modules/channel/channel.model.ts(7,10): error TS2300: Duplicate identifier 'Asset'.`

This is generated in `query-node/generated/graphql-server/src/modules/channel/channel.model.ts`
```
import { Asset } from '../variants/variants.model';
import { Asset } from '../variants/variants.model';
```

**Comment by dzhelezov** [comment]
Fixed in https://github.com/Joystream/hydra/pull/325
