### ISSUE TITLE
Hydra generates 2 TS functions with the same name

### ISSUE THREAD

**Issue by ondratra** [Joystream/hydra#333]
In some cases hydra generate 2 function with the same name.

Use this branch to replicate the problem. https://github.com/ondratra/joystream/tree/hydra_generated_two_functions_same_name

Run
```
yarn
yarn workspace query-node-root build
```

After that, the following file will contain two functions with the same name `videoMediaMetadata`.
`query-node/generated/graphql-server/src/modules/video-media-metadata/video-media-metadata.resolver.ts`

I think the second function should actually be called `videoMediaMetadatas` (ending `s`), and it is some naming problem because if we look at `video-media-encoding.resolver.ts`, there are 2 similar functions called `videoMediaEncodings` and `videoMediaEncoding`.

**Comment by dzhelezov** [comment]
Fixed in 2.1.0-beta.5
