### ISSUE TITLE
Hydra-processor: block-based processing vs event-based processing 

### ISSUE THREAD

**Issue by dzhelezov** [Joystream/hydra#334]
Currently, Hydra processor executes the event mappings in batches of fixed size, no matter if the events come from a single block or different blocks. Apart from being a suboptimal design, the main issue is that the query node can be in an incomplete state. For example, assume that block 1 has events [e1, e2] and block 2 has events [e3, ...., e100]. 

Assume the batch size is 25 events. After the first batch transaction is complete, the query node state will be at event e25, which is an incomplete, as it's in the middle of block 2.

The "right" approach would be to execute the mappings in two transactions:
- [e1, e2]
- [e3, ...., e100]

**Comment by bedeho** [comment]
Is the incomplete state you are referencing an issue because the node cannot recover from a given event/extrinsic index after a fault, it can only recover from a given completed block? Otherwise I don't see in what sense the state can be incomplete.

**Comment by dzhelezov** [comment]
It will recover, but the issue is that the query-node client meanwhile may be seeing a state which does not represent any actual state in the chain. Apart from that, the main motivation for this issue is to be able to effectively version the query node entities by the block hash and be able to perform quick reorgs and/or 'time-travel'.

**Comment by dzhelezov** [comment]
Also not strictly a prerequisite, but the block-based design simplifies the implementation of https://github.com/Joystream/hydra/issues/193 as one can safely but all the required block-level info into the execution context in a fail-safe way.

**Comment by bedeho** [comment]
> It will recover, but the issue is that the query-node clients meanwhile may be seeing a state which does not represent any actual state in the chain.

I cannot conceive of a situation where this is a problem. The mapping author must understand the full semantics of a given event, and if interpreting an event in isolation is in some cases no sufficient to update the query state, then the mapping author must accomodate this correctly. I do not believe we have every come across this. In any case I do no think it should be the role of Hydra to try to generate any kind of guarantees around this.

> Also not strictly a prerequisite, but the block-based design simplifies the implementation of #193 as one can safely put all the required block-level info into the execution context in a fail-safe way.

Ok, I did not fully understand what you meant by this, but is there any downside to doing this?

**Comment by dzhelezov** [comment]
It’s a bad situation when a block has events for entities X and Y, but the query node has updated X but not yet Y, because not all the events in the block has been processed. The state of a query node, should be defined by a single block hash, not by block hash + event id

**Comment by dzhelezov** [comment]
Implemented in https://github.com/Joystream/hydra/pull/347
