### ISSUE TITLE
Composed propositional predicates in entity filtering

### ISSUE THREAD

**Issue by bedeho** [Joystream/hydra#337]
# Background

Currently, its only possible to do filtering of entities with predicates of the following form: `P_1 AND .... AND P_N` where each `P` is a predicate, modelled by a `*WhereInput` value, over the value of a single field, doing things like order, equality and non equality checks.

# Proposal

We would want to have the flexibility to express any predicate structure, by introducing composition as well as `OR` predicates. We may as well also drop the ability to provide multiple `*WhereInput`with implicit AND semantics across them. This should be easy to support by introducing the following in the generated API

```graphql
type *WhereInput {
  AND: [*WhereInput]
  OR: [*WhereInput]
 ...
 ```
 
 See here for more information https://www.opencrud.org/#sec-Data-types.

**Comment by dzhelezov** [comment]
@metmirr Please review and close

**Comment by metmirr** [comment]
Done in https://github.com/Joystream/warthog/releases/tag/v2.30.0
