### ISSUE TITLE
Invalid serialization of Option<Type> extrinsic args

### ISSUE THREAD

**Issue by Lezek123** [Joystream/hydra#393]
Hydra version: `2.1.0-beta.8`

When extrinsics are parsed by the indexer, the extrinsic `args` are serialized to `json`, this results in following entries in the indexer database:

![image](https://user-images.githubusercontent.com/19978260/118117003-4e766300-b3eb-11eb-9f80-7fc0e7b9187c.png)

As you can notice, the `poll` arg (`Option<Poll>`) value has been serialized to empty string. In this case the `Option` was in fact just empty (`null`)

Hydra-typegen generated for me a helper class called `CreateThread_Args` which allows me to retrieve the typed `poll` arg value in the mappings:
```
    get poll(): Option<Poll> {
      return createTypeUnsafe<Option<Poll> & Codec>(typeRegistry, 'Option<Poll>', [this.extrinsic.args[4].value])
    }
```

Unfortunately the value returned by the getter above is invalid and corresponds to `api.createType('Option<Poll>', '')`.
This creates a number of issues as presented in the screenshot below:

![image](https://user-images.githubusercontent.com/19978260/118117617-250a0700-b3ec-11eb-91d4-0e1ce966d6ec.png)

**Comment by dzhelezov** [comment]
The problem is that the value is coerces to an empty string (instead of null)

**Comment by Lezek123** [comment]
I confirm the issue no longer persists after https://github.com/Joystream/hydra/pull/394
