### ISSUE TITLE
Filtering by variant type and properties

### ISSUE THREAD

**Issue by Lezek123** [Joystream/hydra#397]
Moved from: https://github.com/Joystream/joystream/pull/2345#issuecomment-838429476

In the current Olympia input schema it became sort of a standard to have an entity status represented by algebraic type, for example:

```graphql
type WorkerStatusActive @variant {
  # No additional information needed
  _phantom: Int
}

type WorkerStatusLeft @variant {
  "Related event emitted on leaving initialization"
  workerStartedLeavingEvent: WorkerStartedLeavingEvent!

  "Related event emitted (and set) when the unstaking period is finished"
  workerExitedEvent: WorkerExitedEvent
}

type WorkerStatusTerminated @variant {
  "Related event emitted on worker termination"
  terminatedWorkerEvent: TerminatedWorkerEvent!
}

union WorkerStatus = WorkerStatusActive | WorkerStatusLeft | WorkerStatusTerminated

type Worker @entity {
  "Current worker status"
  status: WorkerStatus!
  # ...
}
```

This way it's possible to, for example, include additional event(s) information based on status (ie. here in case the `Worker` was terminated, the frontend can additionally fetch `reason`, `blockNumber` and `blockTimestamp` from the related `TerminatedWorkerEvent`).

Unfortunately, currently in this case it doesn't seem to be possible to create a query that would filter workers by a specific status, for example:

```graphql
query {
	workers(where: { status_json: { __typename_eq: "WorkerStatusActive" } }) {
		status {
			__typename
		}
	}
}
```

Moreover, it also doesn't seem to be possible to filter by other variant fields, even though it's mentioned in the documentation (https://dzhelezov.gitbook.io/hydra/docs/schema-spec/variant-types).

For example the following query:
```graphql
query {
	workingGroupApplications {
		status {
			...on ApplicationStatusAccepted {
				openingFilledEvent {
					id
					createdAt
				}
			}
		}
	}
}
```
Returns:
```json
{
  "data": {
    "workingGroupApplications": [
      {
        "status": {
          "openingFilledEvent": {
            "id": "-69-UePHPb",
            "createdAt": "2021-05-11T10:41:18.000Z"
          }
        }
      },
      # ...
```
But with filters like:
```graphql
  workingGroupApplications(where: { status_json: { openingFilledEvent: { createdAt_gt: "2021-05-10T00:00:00.000Z" } } }) {
```
Or:
```graphql
  workingGroupApplications(where: { status_json: { openingFilledEvent: { id_eq: "-69-UePHPb" } } }) {
```
The query returns no results.

**Comment by metmirr** [comment]
> Unfortunately, currently in this case it doesn't seem to be possible to create a query that would filter workers by a specific status, for example:

Filtering by a specific type is available with `isTypeOf` field:

```graphql
query {
  workers(where: { status_json: { isTypeOf_eq: "WorkerStatusActive" } }) {
    status {
      __typename
    }
  }
}
```

> Moreover, it also doesn't seem to be possible to filter by other variant fields, even though it's mentioned in the documentation (https://dzhelezov.gitbook.io/hydra/docs/schema-spec/variant-types).

Actually, the docs are telling us that we can filter by nested variants, not the relations.
In the example from docs, the `father` is the type of `Poor` which is a union, so the query below is valid:
```graphql
where: { status_json: { father: { isMale_eq: true }} }
```

In your `TerminatedWorkerEvent` seems to be an entity, not a variant right?

**Comment by dzhelezov** [comment]
> Moreover, the example in the docs is not valid anyway. Cli throws an error, I will investigate the error:

Ah yes, I think the docs use invalid schema

**Comment by Lezek123** [comment]
> Filtering by a specific type is available with isTypeOf field

Great, that seems to work, didn't realize this was possible.

> Actually, the docs are telling us that we can filter by nested variants, not the relations.

Oh, I see, I got those mixed up. Is there a chance for filtering by variant relations to be supported?

**Comment by metmirr** [comment]
There are some limitations with variants since they don't own a table in db it's hard to make this feature work. One possible way would be to flatten related entity fields on the variant in format of `fieldName__RelatedEntityName_operator` i.e:

```graphql
workingGroupApplications(
  where: { status_json: { createdAt__OpeningFilledEvent_gt: "2021-05-10T00:00:00.000Z" } } }
)
```

The downside of this approach will be exposing the flattened fields, i.e example:

```graphql
query {
  workingGroupApplications {
    status {
      ... on ApplicationStatusAccepted {
        id__OpeningFilledEvent
        createdAt__OpeningFilledEvent
        openingFilledEvent {
          id
          createdAt
        }
      }
    }
  }
}
```
