### ISSUE TITLE
Broken "OR" clause when filtering variants

### ISSUE THREAD

**Issue by ondratra** [Joystream/hydra#476]
There seems to be a bug in QN `where` conditions containing variant selection in `OR` clause. Only the last option is respected.

Problematic query:
```
query {
  ownedNfts(
    where: {
      OR: [
        { transactionalStatus_json: { isTypeOf_eq: "TransactionalStatusIdle" } },
        {
          transactionalStatus_json: { isTypeOf_eq: "TransactionalStatusBuyNow" },
        }
      ]
    }
  ) {
    id,
    transactionalStatus {
      __typename
    }
  }
}
```
Only NFTs with `TransactionalStatusBuyNow` status will be retrieved.

Query without variant filter seems to be working fine:
```
query {
  ownedNfts(
    where: {
      OR: [{id_eq: 1}, {id_eq: 3}] # assuming these ids exist
    }
  ) {
    id
    transactionalStatus {
      __typename
    }
  }
}
```

Relevant parts of schema:
```
union TransactionalStatus =
    TransactionalStatusIdle
  | TransactionalStatusInitiatedOfferToMember
  | TransactionalStatusAuction
  | TransactionalStatusBuyNow

type TransactionalStatusIdle @variant {
  dummy: Int
}

type TransactionalStatusInitiatedOfferToMember @variant {
  memberId: Int!

  price: BigInt
}

type TransactionalStatusAuction @variant {
  dummy: Int

  auction: Auction!
}

type TransactionalStatusBuyNow @variant {
  price: BigInt!
}

type OwnedNft @entity {
  transactionalStatus: TransactionalStatus!

  ...
}
```

Queries can be tested for example at https://54.172.37.177.nip.io/orion/graphql .

**Comment by kdembler** [comment]
Impact in Atlas at the moment: We can't offer filtering based on multiple possible states for NFT. You can see the design [here](https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?node-id=922%3A135620). This is quite low impact I'd say, we could change the filter to a radio button and allow picking only a single one.

**Comment by bedeho** [comment]
Then lets not have that block the release, just make sure to track the feature in an issue which is properly labelled.

**Comment by ondratra** [comment]
The workaround for this is to query each variant separately and then combine results in the client (JS). I'll try to inspect the root of the problem soon.

**Comment by dmtrjsg** [comment]
awaiting bundling with No fiilter

**Comment by ondratra** [comment]
Fixed in https://github.com/Joystream/warthog/pull/12 + https://github.com/Joystream/hydra/pull/491.
