### ISSUE TITLE
Kusama playground is not reachable

### ISSUE THREAD

**Issue by tt-krzysztof** [Joystream/hydra#508]
Kusama playground (https://indexer-kusama.joystream.app/graphql) is currently not reachable.

**Comment by bedeho** [comment]
Hey, we are no longer maintaining Hydra for external use any longer, consider using Subsquid, which is a spinoff which has much more support: https://github.com/subsquid

**Comment by tt-krzysztof** [comment]
Got it, thanks. Consider removing links from the landing page and docs.
