### ISSUE TITLE
Bug: hydra might skip processing some events when hydra crashes unexpectedly processing a block and then start from the next block 

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/hydra#519]
As reported:
 
![image](https://user-images.githubusercontent.com/37098720/229122385-d32357d3-b765-49b8-9f9d-886c4fa369f1.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1204319283380814) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Why is this possible? wasn't there an explicit transaction lock per block to avoid this?
