### ISSUE TITLE
Missing import for `variant` types

### ISSUE THREAD

**Issue by metmirr** [Joystream/hydra#57]
For the `BigInt` scalar type `BN.js` is used. If a variant type has a field of type `BigInt` then `BN` must be import. Adding import statement to `templates/variants/variants.mst` should be enough.

**Comment by dzhelezov** [comment]
@metmirr What is the status of this issue? Is it already resolved?

**Comment by ondratra** [comment]
This issue has been recently duplicated and resolved (#284). It can be closed now.
