### ISSUE TITLE
Indexer fail to fetch metadata for Joystream dev chain

### ISSUE THREAD

**Issue by metmirr** [Joystream/hydra#7]
Ensuring metadata is not working for `@polkadot/api@0.96.1`. Because of the error api uses the latest metadata for encoding/decoding.

```
Failed to get Metadata for block "0x41145e4919f7696b5c12a74da913f03387b5b21dc6a7f28d1a843ce43604907a", using latest.
TypeError: Cannot destructure property 'knownTypes' of 'undefined' as it is undefined.
```

After doing some debugging I see that `api.registry` is undefined somehow https://github.com/Joystream/joystream/blob/0753bbc913e6073fffeddc344a70473ccf10a76d/query-node/substrate-query-framework/index-builder/src/QueryService.ts#L49

**Comment by dzhelezov** [comment]
@metmirr Can you pls update this status? I think it can be closed now?

**Comment by metmirr** [comment]
No longer an issue, joystream-types are compatible with `@polkadot/api@1.26`
