### ISSUE TITLE
Support multiple mappings 

### ISSUE THREAD

**Issue by dzhelezov** [Joystream/hydra#9]
Currently, the mappings are tracked in a single table `SavedEntityEvents` and the entities share the same table space as the indexer. This is undesirable b/c of the following reasons:
- It is hard to reset a mapping (since it shares the same table space with the indexer)
- It is hard to run multiple mappings simultaneously (as the progress is tracked by a single table)

One of the possible solutions is to store mapping-specific information (progress and the entities) in isolated postgres schemas.

**Comment by bedeho** [comment]
I just want to clarify something here. I typically refer to a mapping as a single function for handling an event or transaction. A search index would be the result of applying a coherent set of mappings to maintain a given search index.

In this issue you are not using `mappings` in that same way, here you are referring to all mappings (as I use the term) related to one API as a single mapping, and you are wanting to allow multiple such APIs to be powered by a single index database.

Am I understanding this correctly?

If I am correct, can we reserve the name mapping to a single function, as I use it, and instead use something like _API index_ for this?

**Comment by dzhelezov** [comment]
Good point, indeed 'mappings' is ambiguous. API Index (or subgraph in TheGraph parlance) would be a better term.
